//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.18 at 03:17:24 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://it.by/tayanovskii/xmlschema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.it.tayanovskii.jd02_09;
