//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.17 at 12:07:30 PM MSK 
//


package by.it.rogov.jd02_09;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JAXP complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JAXP">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="dom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sax" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stax" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="xslt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="xpath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JAXP", propOrder = {
    "dom",
    "sax",
    "stax",
    "xslt",
    "xpath"
})
public class JAXP {

    protected String dom;
    protected String sax;
    protected String stax;
    protected String xslt;
    protected String xpath;

    /**
     * Gets the value of the dom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDom() {
        return dom;
    }

    /**
     * Sets the value of the dom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDom(String value) {
        this.dom = value;
    }

    /**
     * Gets the value of the sax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSax() {
        return sax;
    }

    /**
     * Sets the value of the sax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSax(String value) {
        this.sax = value;
    }

    /**
     * Gets the value of the stax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStax() {
        return stax;
    }

    /**
     * Sets the value of the stax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStax(String value) {
        this.stax = value;
    }

    /**
     * Gets the value of the xslt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXslt() {
        return xslt;
    }

    /**
     * Sets the value of the xslt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXslt(String value) {
        this.xslt = value;
    }

    /**
     * Gets the value of the xpath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXpath() {
        return xpath;
    }

    /**
     * Sets the value of the xpath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXpath(String value) {
        this.xpath = value;
    }

}
