//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.06.15 at 06:26:19 AM GMT+03:00
//


package by.it.kasiyanov.jd02_09;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TravelAgent" type="{http://jd02_09.kasiyanov.it.by}TravelAgent" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "travelAgent"
})
@XmlRootElement(name = "TravelAgents")
public class TravelAgents {

    @XmlElement(name = "TravelAgent", required = true)
    protected List<TravelAgent> travelAgent;

    /**
     * Gets the value of the travelAgent property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the travelAgent property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTravelAgent().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TravelAgent }
     *
     *
     */
    public List<TravelAgent> getTravelAgent() {
        if (travelAgent == null) {
            travelAgent = new ArrayList<TravelAgent>();
        }
        return this.travelAgent;
    }

    @Override
    public String toString() {
        return "TravelAgents{" +
                "travelAgent=" + travelAgent +
                '}';
    }
}
