//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.06.15 at 06:26:19 AM GMT+03:00
//


package by.it.kasiyanov.jd02_09;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TravelOffers complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TravelOffers">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="TravelOffer" type="{http://jd02_09.kasiyanov.it.by}TravelOffer" maxOccurs="unbounded"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TravelOffers", propOrder = {
        "travelOffer"
})
public class TravelOffers {

    @XmlElement(name = "TravelOffer")
    protected List<TravelOffer> travelOffer;

    /**
     * Gets the value of the travelOffer property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the travelOffer property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTravelOffer().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TravelOffer }
     *
     *
     */
    public List<TravelOffer> getTravelOffer() {
        if (travelOffer == null) {
            travelOffer = new ArrayList<TravelOffer>();
        }
        return this.travelOffer;
    }

    @Override
    public String toString() {
        return "TravelOffers{" +
                "travelOffer=" + travelOffer +
                '}';
    }
}
