//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.06.15 at 06:26:19 AM GMT+03:00
//


package by.it.kasiyanov.jd02_09;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TravelOffer complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TravelOffer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TypeOfTrevel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Destination" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Hotel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LevelOfAccommodation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NumberOfNight" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Price" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TravelOffer", propOrder = {
        "description",
        "typeOfTrevel",
        "destination",
        "hotel",
        "levelOfAccommodation",
        "numberOfNight",
        "price"
})
public class TravelOffer {

    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "TypeOfTrevel", required = true)
    protected String typeOfTrevel;
    @XmlElement(name = "Destination", required = true)
    protected String destination;
    @XmlElement(name = "Hotel", required = true)
    protected String hotel;
    @XmlElement(name = "LevelOfAccommodation", required = true)
    protected String levelOfAccommodation;
    @XmlElement(name = "NumberOfNight", required = true)
    protected BigInteger numberOfNight;
    @XmlElement(name = "Price")
    protected double price;

    /**
     * Gets the value of the description property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the typeOfTrevel property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTypeOfTrevel() {
        return typeOfTrevel;
    }

    /**
     * Sets the value of the typeOfTrevel property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTypeOfTrevel(String value) {
        this.typeOfTrevel = value;
    }

    /**
     * Gets the value of the destination property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDestination(String value) {
        this.destination = value;
    }

    /**
     * Gets the value of the hotel property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHotel() {
        return hotel;
    }

    /**
     * Sets the value of the hotel property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHotel(String value) {
        this.hotel = value;
    }

    /**
     * Gets the value of the levelOfAccommodation property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLevelOfAccommodation() {
        return levelOfAccommodation;
    }

    /**
     * Sets the value of the levelOfAccommodation property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLevelOfAccommodation(String value) {
        this.levelOfAccommodation = value;
    }

    /**
     * Gets the value of the numberOfNight property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getNumberOfNight() {
        return numberOfNight;
    }

    /**
     * Sets the value of the numberOfNight property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setNumberOfNight(BigInteger value) {
        this.numberOfNight = value;
    }

    /**
     * Gets the value of the price property.
     *
     */
    public double getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     *
     */
    public void setPrice(double value) {
        this.price = value;
    }

    @Override
    public String toString() {
        return "TravelOffer{" +
                "description='" + description + '\'' +
                ", typeOfTrevel='" + typeOfTrevel + '\'' +
                ", destination='" + destination + '\'' +
                ", hotel='" + hotel + '\'' +
                ", levelOfAccommodation='" + levelOfAccommodation + '\'' +
                ", numberOfNight=" + numberOfNight +
                ", price=" + price +
                '}';
    }
}
